// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type SendEmailReq struct {
	Email string `json:"email"`
}

type UserDetailsResp struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
